version: '3.8'

services:
  mongo1:
    image: mongo:latest
    container_name: mongo1
    networks:
      - mongo-replica-set
    ports:
      - 27017:27017
    volumes:
      - mongo1-data:/data/db
    command: ["mongod", "--replSet", "rs0", "--bind_ip_all"]

  mongo2:
    image: mongo:latest
    container_name: mongo2
    networks:
      - mongo-replica-set
    ports:
      - 27018:27017
    volumes:
      - mongo2-data:/data/db
    command: ["mongod", "--replSet", "rs0", "--bind_ip_all"]

  mongo3:
    image: mongo:latest
    container_name: mongo3
    networks:
      - mongo-replica-set
    ports:
      - 27019:27017
    volumes:
      - mongo3-data:/data/db
    command: ["mongod", "--replSet", "rs0", "--bind_ip_all"]

networks:
  mongo-replica-set:

volumes:
  mongo1-data:
  mongo2-data:
  mongo3-data:
